language: ruby
rvm:
  - 2.2

dist: trusty
sudo: false

branches:
  only:
    - poc
    - gh-pages

cache:
  bundler: true
  yarn: true
  directories:
    - node_modules # NPM packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  CXX=g++-4.8

before_install:
  - nvm install 6
  - npm install gulp-cli -g
  - npm install git+https://git@github.com/gulpjs/gulp.git#4.0 --save-dev
  - npm install yarn -g
  - yarn

script: gulp build --prod

before_deploy:
  - cp CNAME dist/ # TODO: Quick-fix

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: poc

after_deploy:
  - gulp submit_sitemap
