# Made Mistakes Gemfile
source "https://rubygems.org"

gem "jekyll"
gem "jekyll-sitemap"
gem "sass"
gem "bourbon"
gem "neat"
gem "octopress", "~> 3.0.0.rc.12"
gem "jekyll-assets"
gem "uglifier"
gem "font-awesome-sass", "~> 4.2.0"
gem "autoprefixer-rails"
gem "jekyll-archives"
gem "rouge"
