# Made Mistakes Gemfile
source "https://rubygems.org"

gem "jekyll"
gem "jekyll-sitemap"
gem "sass"
gem "susy"
gem "breakpoint"
gem "bourbon"
gem "neat"
gem "jekyll-assets"
gem "uglifier"
gem "autoprefixer-rails"
gem "jekyll-archives"
gem "rouge"
